/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CTraceNet */

#ifndef _Included_CTraceNet
#define _Included_CTraceNet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CTraceNet
 * Method:    runTrace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CTraceNet_runTrace
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
